# 04 数据操作 数据预处理

In [1]:
import torch

In [2]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [8]:
torch.tensor([1.0, 2, 4, 8])  # 创造浮点数组 

tensor([1., 2., 4., 8.])

In [10]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4, ], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [14]:
X.sum()

tensor(66.)

In [18]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [19]:
a = torch.tensor([3.5])
a.item(), float(a)

(3.5, 3.5)

In [40]:
import numpy as np
import pandas as pd
data = np.random.randn(12).reshape(3, 4)
data[2, 2] = np.nan
data = pd.DataFrame(data)
data

0         1         2         3
0  0.880328 -0.993549  0.505318 -0.193174
1  0.807602 -0.072603 -0.775386 -0.227318
2  0.968191 -0.009449       NaN -1.186740

In [41]:
data = data.fillna(data.mean())
data

0         1         2         3
0  0.880328 -0.993549  0.505318 -0.193174
1  0.807602 -0.072603 -0.775386 -0.227318
2  0.968191 -0.009449 -0.135034 -1.186740

In [44]:
data = np.random.randn(12).reshape(3, 4)
data = pd.DataFrame(data)
data['name'] = np.array(['Pave', 'NA', 'NA'])
data

0         1         2         3  name
0 -0.057792 -0.822247  1.919392 -1.134288  Pave
1 -0.492331 -1.530759 -0.078065 -0.434588    NA
2 -1.314765  2.139398  0.830189 -0.973914    NA

In [45]:
data = pd.get_dummies(data, dummy_na=False)
data

0         1         2         3  name_NA  name_Pave
0 -0.057792 -0.822247  1.919392 -1.134288        0          1
1 -0.492331 -1.530759 -0.078065 -0.434588        1          0
2 -1.314765  2.139398  0.830189 -0.973914        1          0

# 05 线性代数

In [1]:
import torch
x = torch.arange(24).reshape(2, 3, 4)
y = x.clone()
id(x), id(y)

(1963466121280, 1963466121360)

In [4]:
x.sum(dim=0), x.sum(axis=0)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]))

In [6]:
A = torch.rand(5, 4)
x = torch.rand(4)
torch.mv(A, x)

tensor([0.8054, 1.1660, 0.5680, 1.2312, 0.9003])

In [9]:
A = torch.ones((2, 5, 4))
A.sum(axis=[0, 2], keepdims=True).shape

torch.Size([1, 5, 1])